name: Build
on:
  pull_request:
    branches:
      - master
jobs:
  richgo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t pawzio/richgo:1.14.3-alpine3.11 image/richgo/.
  compose-make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t pawzio/compose-make:debian-1.25.5 image/compose-make/.
  godacy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t pawzio/godacy:1.14.3-alpine3.11 image/godacy/.
