name: Build
on:
  pull_request:
    branches:
      - master
jobs:
  richgo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: pawzio/richgo
          tags: 1.14.3-alpine3.11
          path: image/richgo/.
          push: false
  compose-make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: pawzio/compose-make
          tags: debian-1.25.5
          path: image/compose-make/.
          push: false
  godacy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: pawzio/godacy
          tags: 1.14.3-alpine3.11
          path: image/godacy/.
          push: false
  gobase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: pawzio/gobase
          tags: 1.14.6
          path: image/gobase/.
          push: false
